# Generated by Django 4.0 on 2021-12-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=30)),
                ('is_critical', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
