# Generated by Django 4.0 on 2021-12-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_service_delete_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_number', models.IntegerField(primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=30)),
                ('is_normal', models.BooleanField(default=True)),
            ],
        ),
    ]
